name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  merge_group:

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run type-check
        run: pnpm type-check

      - name: Run lint
        run: pnpm lint
