org: sickholdingdev
app: tldw-aws-api
service: tldw-aws-api
frameworkVersion: "3"

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!venv/**"

custom:
  pythonRequirements:
    slim: true
    layer: true

provider:
  name: aws
  runtime: python3.9
  deploymentMethod: direct

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  youtube_transcript:
    handler: index.generateTranscript
    module: functions.youtube_transcript
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /generateTranscript
          method: get
  generate_embeddings:
    handler: index.generateEmbeddings
    module: functions.generate_embeddings
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /generateEmbeddings
          method: get
  pinecone_query:
    handler: index.generatePinconeQuery
    module: functions.pinecone_query
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /generatePinconeQuery
          method: get
  answer_question:
    handler: index.generateAnswer
    module: functions.answer_questions
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /generateAnswer
          method: get
