org: sickholdingdev
app: tldw-aws-api
service: tldw-aws-api
frameworkVersion: "3"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  deploymentMethod: direct

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  youtube_transcript:
    handler: functions.youtube_transcript.generateTranscript
    events:
      - httpApi:
          path: /generateTranscript
          method: get
  generate_embeddings:
    handler: functions.generate_embeddings.generateEmbeddings
    events:
      - httpApi:
          path: /generateEmbeddings
          method: get
  pinecone_query:
    handler: functions.pinecone_query.generatePinconeQuery
    events:
      - httpApi:
          path: /generatePinconeQuery
          method: get
  answer_question:
    handler: functions.answer_question.generateAnswer
    events:
      - httpApi:
          path: /generateAnswer
          method: get
