org: sickholdingdev
app: tldw-aws-api
service: tldw-aws-api
frameworkVersion: "3"

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!venv/**"

custom:
  pythonRequirements:
    slim: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  deploymentMethod: direct
  environment:
    YOUTUBE_API_KEY: AIzaSyD1f0WU3DFhib7rG4dcM44lHW_gGz7CQWg

functions:
  youtube_transcript:
    handler: index.generateTranscript
    module: youtube_transcript_module
    events:
      - httpApi:
          path: /generateTranscript
          method: get
