org: jhamilton
app: tldw-aws-api
service: tldw-aws-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  deploymentMethod: direct

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  youtube_transcript:
    handler: functions.youtube_transcript.index.generateTranscript
    events:
      - httpApi:
          path: /generateTranscript
          method: get
    package:
      include:
        - ./functions/youtube_transcript/python/site-packages
